package com.adccadc.rust;

import com.adccadc.rust.block.Modblocks;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;

import java.util.HashMap;
import java.util.Map;

public class CauldronMap {
    public static Map<Block, Block> CAULDRON_TO_WATER_CAULDRON = new HashMap<>();
    static {
        CAULDRON_TO_WATER_CAULDRON.put(Blocks.CAULDRON, Blocks.WATER_CAULDRON);
        CAULDRON_TO_WATER_CAULDRON.put(Blocks.LAVA_CAULDRON, Blocks.WATER_CAULDRON);
        CAULDRON_TO_WATER_CAULDRON.put(Blocks.POWDER_SNOW_CAULDRON, Blocks.WATER_CAULDRON);
        CAULDRON_TO_WATER_CAULDRON.put(Modblocks.EXPOSED_CAULDRON, Modblocks.EXPOSED_WATER_CAULDRON);
        CAULDRON_TO_WATER_CAULDRON.put(Modblocks.EXPOSED_WATER_CAULDRON, Modblocks.EXPOSED_WATER_CAULDRON);
        CAULDRON_TO_WATER_CAULDRON.put(Modblocks.EXPOSED_LAVA_CAULDRON, Modblocks.EXPOSED_WATER_CAULDRON);
        CAULDRON_TO_WATER_CAULDRON.put(Modblocks.EXPOSED_POWDER_SNOW_CAULDRON, Modblocks.EXPOSED_WATER_CAULDRON);
        CAULDRON_TO_WATER_CAULDRON.put(Modblocks.WEATHERED_CAULDRON, Modblocks.WEATHERED_WATER_CAULDRON);
        CAULDRON_TO_WATER_CAULDRON.put(Modblocks.WEATHERED_WATER_CAULDRON, Modblocks.WEATHERED_WATER_CAULDRON);
        CAULDRON_TO_WATER_CAULDRON.put(Modblocks.WEATHERED_LAVA_CAULDRON, Modblocks.WEATHERED_WATER_CAULDRON);
        CAULDRON_TO_WATER_CAULDRON.put(Modblocks.WEATHERED_POWDER_SNOW_CAULDRON, Modblocks.WEATHERED_WATER_CAULDRON);
        CAULDRON_TO_WATER_CAULDRON.put(Modblocks.OXIDIZED_CAULDRON, Modblocks.OXIDIZED_WATER_CAULDRON);
        CAULDRON_TO_WATER_CAULDRON.put(Modblocks.OXIDIZED_WATER_CAULDRON, Modblocks.OXIDIZED_WATER_CAULDRON);
        CAULDRON_TO_WATER_CAULDRON.put(Modblocks.OXIDIZED_LAVA_CAULDRON, Modblocks.OXIDIZED_WATER_CAULDRON);
        CAULDRON_TO_WATER_CAULDRON.put(Modblocks.OXIDIZED_POWDER_SNOW_CAULDRON, Modblocks.OXIDIZED_WATER_CAULDRON);
        CAULDRON_TO_WATER_CAULDRON.put(Modblocks.WAXED_CAULDRON, Modblocks.WAXED_WATER_CAULDRON);
        CAULDRON_TO_WATER_CAULDRON.put(Modblocks.WAXED_WATER_CAULDRON, Modblocks.WAXED_WATER_CAULDRON);
        CAULDRON_TO_WATER_CAULDRON.put(Modblocks.WAXED_LAVA_CAULDRON, Modblocks.WAXED_WATER_CAULDRON);
        CAULDRON_TO_WATER_CAULDRON.put(Modblocks.WAXED_POWDER_SNOW_CAULDRON, Modblocks.WAXED_WATER_CAULDRON);
        CAULDRON_TO_WATER_CAULDRON.put(Modblocks.WAXED_EXPOSED_CAULDRON, Modblocks.WAXED_EXPOSED_WATER_CAULDRON);
        CAULDRON_TO_WATER_CAULDRON.put(Modblocks.WAXED_EXPOSED_WATER_CAULDRON, Modblocks.WAXED_EXPOSED_WATER_CAULDRON);
        CAULDRON_TO_WATER_CAULDRON.put(Modblocks.WAXED_EXPOSED_LAVA_CAULDRON, Modblocks.WAXED_EXPOSED_WATER_CAULDRON);
        CAULDRON_TO_WATER_CAULDRON.put(Modblocks.WAXED_EXPOSED_POWDER_SNOW_CAULDRON, Modblocks.WAXED_EXPOSED_WATER_CAULDRON);
        CAULDRON_TO_WATER_CAULDRON.put(Modblocks.WAXED_WEATHERED_CAULDRON, Modblocks.WAXED_WEATHERED_WATER_CAULDRON);
        CAULDRON_TO_WATER_CAULDRON.put(Modblocks.WAXED_WEATHERED_WATER_CAULDRON, Modblocks.WAXED_WEATHERED_WATER_CAULDRON);
        CAULDRON_TO_WATER_CAULDRON.put(Modblocks.WAXED_WEATHERED_LAVA_CAULDRON, Modblocks.WAXED_WEATHERED_WATER_CAULDRON);
        CAULDRON_TO_WATER_CAULDRON.put(Modblocks.WAXED_WEATHERED_POWDER_SNOW_CAULDRON, Modblocks.WAXED_WEATHERED_WATER_CAULDRON);
        CAULDRON_TO_WATER_CAULDRON.put(Modblocks.WAXED_OXIDIZED_CAULDRON, Modblocks.WAXED_OXIDIZED_WATER_CAULDRON);
        CAULDRON_TO_WATER_CAULDRON.put(Modblocks.WAXED_OXIDIZED_WATER_CAULDRON, Modblocks.WAXED_OXIDIZED_WATER_CAULDRON);
        CAULDRON_TO_WATER_CAULDRON.put(Modblocks.WAXED_OXIDIZED_LAVA_CAULDRON, Modblocks.WAXED_OXIDIZED_WATER_CAULDRON);
        CAULDRON_TO_WATER_CAULDRON.put(Modblocks.WAXED_OXIDIZED_POWDER_SNOW_CAULDRON, Modblocks.WAXED_OXIDIZED_WATER_CAULDRON);
    }

    public static Map<Block, Block> CAULDRON_TO_LAVA_CAULDRON = new HashMap<>();
    static {
        CAULDRON_TO_LAVA_CAULDRON.put(Blocks.CAULDRON, Blocks.LAVA_CAULDRON);
        CAULDRON_TO_LAVA_CAULDRON.put(Blocks.LAVA_CAULDRON, Blocks.LAVA_CAULDRON);
        CAULDRON_TO_LAVA_CAULDRON.put(Blocks.POWDER_SNOW_CAULDRON, Blocks.LAVA_CAULDRON);
        CAULDRON_TO_LAVA_CAULDRON.put(Modblocks.EXPOSED_CAULDRON, Modblocks.EXPOSED_LAVA_CAULDRON);
        CAULDRON_TO_LAVA_CAULDRON.put(Modblocks.EXPOSED_WATER_CAULDRON, Modblocks.EXPOSED_LAVA_CAULDRON);
        CAULDRON_TO_LAVA_CAULDRON.put(Modblocks.EXPOSED_LAVA_CAULDRON, Modblocks.EXPOSED_LAVA_CAULDRON);
        CAULDRON_TO_LAVA_CAULDRON.put(Modblocks.EXPOSED_POWDER_SNOW_CAULDRON, Modblocks.EXPOSED_LAVA_CAULDRON);
        CAULDRON_TO_LAVA_CAULDRON.put(Modblocks.WEATHERED_CAULDRON, Modblocks.WEATHERED_LAVA_CAULDRON);
        CAULDRON_TO_LAVA_CAULDRON.put(Modblocks.WEATHERED_WATER_CAULDRON, Modblocks.WEATHERED_LAVA_CAULDRON);
        CAULDRON_TO_LAVA_CAULDRON.put(Modblocks.WEATHERED_LAVA_CAULDRON, Modblocks.WEATHERED_LAVA_CAULDRON);
        CAULDRON_TO_LAVA_CAULDRON.put(Modblocks.WEATHERED_POWDER_SNOW_CAULDRON, Modblocks.WEATHERED_LAVA_CAULDRON);
        CAULDRON_TO_LAVA_CAULDRON.put(Modblocks.OXIDIZED_CAULDRON, Modblocks.OXIDIZED_LAVA_CAULDRON);
        CAULDRON_TO_LAVA_CAULDRON.put(Modblocks.OXIDIZED_WATER_CAULDRON, Modblocks.OXIDIZED_LAVA_CAULDRON);
        CAULDRON_TO_LAVA_CAULDRON.put(Modblocks.OXIDIZED_LAVA_CAULDRON, Modblocks.OXIDIZED_LAVA_CAULDRON);
        CAULDRON_TO_LAVA_CAULDRON.put(Modblocks.OXIDIZED_POWDER_SNOW_CAULDRON, Modblocks.OXIDIZED_LAVA_CAULDRON);
        CAULDRON_TO_LAVA_CAULDRON.put(Modblocks.WAXED_CAULDRON, Modblocks.WAXED_LAVA_CAULDRON);
        CAULDRON_TO_LAVA_CAULDRON.put(Modblocks.WAXED_WATER_CAULDRON, Modblocks.WAXED_LAVA_CAULDRON);
        CAULDRON_TO_LAVA_CAULDRON.put(Modblocks.WAXED_LAVA_CAULDRON, Modblocks.WAXED_LAVA_CAULDRON);
        CAULDRON_TO_LAVA_CAULDRON.put(Modblocks.WAXED_POWDER_SNOW_CAULDRON, Modblocks.WAXED_LAVA_CAULDRON);
        CAULDRON_TO_LAVA_CAULDRON.put(Modblocks.WAXED_EXPOSED_CAULDRON, Modblocks.WAXED_EXPOSED_LAVA_CAULDRON);
        CAULDRON_TO_LAVA_CAULDRON.put(Modblocks.WAXED_EXPOSED_WATER_CAULDRON, Modblocks.WAXED_EXPOSED_LAVA_CAULDRON);
        CAULDRON_TO_LAVA_CAULDRON.put(Modblocks.WAXED_EXPOSED_LAVA_CAULDRON, Modblocks.WAXED_EXPOSED_LAVA_CAULDRON);
        CAULDRON_TO_LAVA_CAULDRON.put(Modblocks.WAXED_EXPOSED_POWDER_SNOW_CAULDRON, Modblocks.WAXED_EXPOSED_LAVA_CAULDRON);
        CAULDRON_TO_LAVA_CAULDRON.put(Modblocks.WAXED_WEATHERED_CAULDRON, Modblocks.WAXED_WEATHERED_LAVA_CAULDRON);
        CAULDRON_TO_LAVA_CAULDRON.put(Modblocks.WAXED_WEATHERED_WATER_CAULDRON, Modblocks.WAXED_WEATHERED_LAVA_CAULDRON);
        CAULDRON_TO_LAVA_CAULDRON.put(Modblocks.WAXED_WEATHERED_LAVA_CAULDRON, Modblocks.WAXED_WEATHERED_LAVA_CAULDRON);
        CAULDRON_TO_LAVA_CAULDRON.put(Modblocks.WAXED_WEATHERED_POWDER_SNOW_CAULDRON, Modblocks.WAXED_WEATHERED_LAVA_CAULDRON);
        CAULDRON_TO_LAVA_CAULDRON.put(Modblocks.WAXED_OXIDIZED_CAULDRON, Modblocks.WAXED_OXIDIZED_LAVA_CAULDRON);
        CAULDRON_TO_LAVA_CAULDRON.put(Modblocks.WAXED_OXIDIZED_WATER_CAULDRON, Modblocks.WAXED_OXIDIZED_LAVA_CAULDRON);
        CAULDRON_TO_LAVA_CAULDRON.put(Modblocks.WAXED_OXIDIZED_LAVA_CAULDRON, Modblocks.WAXED_OXIDIZED_LAVA_CAULDRON);
        CAULDRON_TO_LAVA_CAULDRON.put(Modblocks.WAXED_OXIDIZED_POWDER_SNOW_CAULDRON, Modblocks.WAXED_OXIDIZED_LAVA_CAULDRON);
    }

    public static Map<Block, Block> CAULDRON_TO_POWDER_SNOW_CAULDRON = new HashMap<>();
    static {
        CAULDRON_TO_POWDER_SNOW_CAULDRON.put(Blocks.CAULDRON, Blocks.POWDER_SNOW_CAULDRON);
        CAULDRON_TO_POWDER_SNOW_CAULDRON.put(Blocks.LAVA_CAULDRON, Blocks.POWDER_SNOW_CAULDRON);
        CAULDRON_TO_POWDER_SNOW_CAULDRON.put(Blocks.POWDER_SNOW_CAULDRON, Blocks.POWDER_SNOW_CAULDRON);
        CAULDRON_TO_POWDER_SNOW_CAULDRON.put(Modblocks.EXPOSED_CAULDRON, Modblocks.EXPOSED_POWDER_SNOW_CAULDRON);
        CAULDRON_TO_POWDER_SNOW_CAULDRON.put(Modblocks.EXPOSED_WATER_CAULDRON, Modblocks.EXPOSED_POWDER_SNOW_CAULDRON);
        CAULDRON_TO_POWDER_SNOW_CAULDRON.put(Modblocks.EXPOSED_LAVA_CAULDRON, Modblocks.EXPOSED_POWDER_SNOW_CAULDRON);
        CAULDRON_TO_POWDER_SNOW_CAULDRON.put(Modblocks.EXPOSED_POWDER_SNOW_CAULDRON, Modblocks.EXPOSED_POWDER_SNOW_CAULDRON);
        CAULDRON_TO_POWDER_SNOW_CAULDRON.put(Modblocks.WEATHERED_CAULDRON, Modblocks.WEATHERED_POWDER_SNOW_CAULDRON);
        CAULDRON_TO_POWDER_SNOW_CAULDRON.put(Modblocks.WEATHERED_WATER_CAULDRON, Modblocks.WEATHERED_POWDER_SNOW_CAULDRON);
        CAULDRON_TO_POWDER_SNOW_CAULDRON.put(Modblocks.WEATHERED_LAVA_CAULDRON, Modblocks.WEATHERED_POWDER_SNOW_CAULDRON);
        CAULDRON_TO_POWDER_SNOW_CAULDRON.put(Modblocks.WEATHERED_POWDER_SNOW_CAULDRON, Modblocks.WEATHERED_POWDER_SNOW_CAULDRON);
        CAULDRON_TO_POWDER_SNOW_CAULDRON.put(Modblocks.OXIDIZED_CAULDRON, Modblocks.OXIDIZED_POWDER_SNOW_CAULDRON);
        CAULDRON_TO_POWDER_SNOW_CAULDRON.put(Modblocks.OXIDIZED_WATER_CAULDRON, Modblocks.OXIDIZED_POWDER_SNOW_CAULDRON);
        CAULDRON_TO_POWDER_SNOW_CAULDRON.put(Modblocks.OXIDIZED_LAVA_CAULDRON, Modblocks.OXIDIZED_POWDER_SNOW_CAULDRON);
        CAULDRON_TO_POWDER_SNOW_CAULDRON.put(Modblocks.OXIDIZED_POWDER_SNOW_CAULDRON, Modblocks.OXIDIZED_POWDER_SNOW_CAULDRON);
        CAULDRON_TO_POWDER_SNOW_CAULDRON.put(Modblocks.WAXED_CAULDRON, Modblocks.WAXED_POWDER_SNOW_CAULDRON);
        CAULDRON_TO_POWDER_SNOW_CAULDRON.put(Modblocks.WAXED_WATER_CAULDRON, Modblocks.WAXED_POWDER_SNOW_CAULDRON);
        CAULDRON_TO_POWDER_SNOW_CAULDRON.put(Modblocks.WAXED_LAVA_CAULDRON, Modblocks.WAXED_POWDER_SNOW_CAULDRON);
        CAULDRON_TO_POWDER_SNOW_CAULDRON.put(Modblocks.WAXED_POWDER_SNOW_CAULDRON, Modblocks.WAXED_POWDER_SNOW_CAULDRON);
        CAULDRON_TO_POWDER_SNOW_CAULDRON.put(Modblocks.WAXED_EXPOSED_CAULDRON, Modblocks.WAXED_EXPOSED_POWDER_SNOW_CAULDRON);
        CAULDRON_TO_POWDER_SNOW_CAULDRON.put(Modblocks.WAXED_EXPOSED_WATER_CAULDRON, Modblocks.WAXED_EXPOSED_POWDER_SNOW_CAULDRON);
        CAULDRON_TO_POWDER_SNOW_CAULDRON.put(Modblocks.WAXED_EXPOSED_LAVA_CAULDRON, Modblocks.WAXED_EXPOSED_POWDER_SNOW_CAULDRON);
        CAULDRON_TO_POWDER_SNOW_CAULDRON.put(Modblocks.WAXED_EXPOSED_POWDER_SNOW_CAULDRON, Modblocks.WAXED_EXPOSED_POWDER_SNOW_CAULDRON);
        CAULDRON_TO_POWDER_SNOW_CAULDRON.put(Modblocks.WAXED_WEATHERED_CAULDRON, Modblocks.WAXED_WEATHERED_POWDER_SNOW_CAULDRON);
        CAULDRON_TO_POWDER_SNOW_CAULDRON.put(Modblocks.WAXED_WEATHERED_WATER_CAULDRON, Modblocks.WAXED_WEATHERED_POWDER_SNOW_CAULDRON);
        CAULDRON_TO_POWDER_SNOW_CAULDRON.put(Modblocks.WAXED_WEATHERED_LAVA_CAULDRON, Modblocks.WAXED_WEATHERED_POWDER_SNOW_CAULDRON);
        CAULDRON_TO_POWDER_SNOW_CAULDRON.put(Modblocks.WAXED_WEATHERED_POWDER_SNOW_CAULDRON, Modblocks.WAXED_WEATHERED_POWDER_SNOW_CAULDRON);
        CAULDRON_TO_POWDER_SNOW_CAULDRON.put(Modblocks.WAXED_OXIDIZED_CAULDRON, Modblocks.WAXED_OXIDIZED_POWDER_SNOW_CAULDRON);
        CAULDRON_TO_POWDER_SNOW_CAULDRON.put(Modblocks.WAXED_OXIDIZED_WATER_CAULDRON, Modblocks.WAXED_OXIDIZED_POWDER_SNOW_CAULDRON);
        CAULDRON_TO_POWDER_SNOW_CAULDRON.put(Modblocks.WAXED_OXIDIZED_LAVA_CAULDRON, Modblocks.WAXED_OXIDIZED_POWDER_SNOW_CAULDRON);
        CAULDRON_TO_POWDER_SNOW_CAULDRON.put(Modblocks.WAXED_OXIDIZED_POWDER_SNOW_CAULDRON, Modblocks.WAXED_OXIDIZED_POWDER_SNOW_CAULDRON);
    }

    public static Map<Block, Block> CAULDRON_TO_EMPTY_CAULDRON = new HashMap<>();
    static {
        CAULDRON_TO_EMPTY_CAULDRON.put(Blocks.WATER_CAULDRON, Blocks.CAULDRON);
        CAULDRON_TO_EMPTY_CAULDRON.put(Blocks.LAVA_CAULDRON, Blocks.CAULDRON);
        CAULDRON_TO_EMPTY_CAULDRON.put(Blocks.POWDER_SNOW_CAULDRON, Blocks.CAULDRON);
        CAULDRON_TO_EMPTY_CAULDRON.put(Modblocks.EXPOSED_WATER_CAULDRON, Modblocks.EXPOSED_CAULDRON);
        CAULDRON_TO_EMPTY_CAULDRON.put(Modblocks.EXPOSED_LAVA_CAULDRON, Modblocks.EXPOSED_CAULDRON);
        CAULDRON_TO_EMPTY_CAULDRON.put(Modblocks.EXPOSED_POWDER_SNOW_CAULDRON, Modblocks.EXPOSED_CAULDRON);
        CAULDRON_TO_EMPTY_CAULDRON.put(Modblocks.WEATHERED_WATER_CAULDRON, Modblocks.WEATHERED_CAULDRON);
        CAULDRON_TO_EMPTY_CAULDRON.put(Modblocks.WEATHERED_LAVA_CAULDRON, Modblocks.WEATHERED_CAULDRON);
        CAULDRON_TO_EMPTY_CAULDRON.put(Modblocks.WEATHERED_POWDER_SNOW_CAULDRON, Modblocks.WEATHERED_CAULDRON);
        CAULDRON_TO_EMPTY_CAULDRON.put(Modblocks.OXIDIZED_WATER_CAULDRON, Modblocks.OXIDIZED_CAULDRON);
        CAULDRON_TO_EMPTY_CAULDRON.put(Modblocks.OXIDIZED_LAVA_CAULDRON, Modblocks.OXIDIZED_CAULDRON);
        CAULDRON_TO_EMPTY_CAULDRON.put(Modblocks.OXIDIZED_POWDER_SNOW_CAULDRON, Modblocks.OXIDIZED_CAULDRON);
        CAULDRON_TO_EMPTY_CAULDRON.put(Modblocks.WAXED_WATER_CAULDRON, Modblocks.WAXED_CAULDRON);
        CAULDRON_TO_EMPTY_CAULDRON.put(Modblocks.WAXED_LAVA_CAULDRON, Modblocks.WAXED_CAULDRON);
        CAULDRON_TO_EMPTY_CAULDRON.put(Modblocks.WAXED_POWDER_SNOW_CAULDRON, Modblocks.WAXED_CAULDRON);
        CAULDRON_TO_EMPTY_CAULDRON.put(Modblocks.WAXED_EXPOSED_WATER_CAULDRON, Modblocks.WAXED_EXPOSED_CAULDRON);
        CAULDRON_TO_EMPTY_CAULDRON.put(Modblocks.WAXED_EXPOSED_LAVA_CAULDRON, Modblocks.WAXED_EXPOSED_CAULDRON);
        CAULDRON_TO_EMPTY_CAULDRON.put(Modblocks.WAXED_EXPOSED_POWDER_SNOW_CAULDRON, Modblocks.WAXED_EXPOSED_CAULDRON);
        CAULDRON_TO_EMPTY_CAULDRON.put(Modblocks.WAXED_WEATHERED_WATER_CAULDRON, Modblocks.WAXED_WEATHERED_CAULDRON);
        CAULDRON_TO_EMPTY_CAULDRON.put(Modblocks.WAXED_WEATHERED_LAVA_CAULDRON, Modblocks.WAXED_WEATHERED_CAULDRON);
        CAULDRON_TO_EMPTY_CAULDRON.put(Modblocks.WAXED_WEATHERED_POWDER_SNOW_CAULDRON, Modblocks.WAXED_WEATHERED_CAULDRON);
        CAULDRON_TO_EMPTY_CAULDRON.put(Modblocks.WAXED_OXIDIZED_WATER_CAULDRON, Modblocks.WAXED_OXIDIZED_CAULDRON);
        CAULDRON_TO_EMPTY_CAULDRON.put(Modblocks.WAXED_OXIDIZED_LAVA_CAULDRON, Modblocks.WAXED_OXIDIZED_CAULDRON);
        CAULDRON_TO_EMPTY_CAULDRON.put(Modblocks.WAXED_OXIDIZED_POWDER_SNOW_CAULDRON, Modblocks.WAXED_OXIDIZED_CAULDRON);
    }
}
