package com.adccadc.rust;

import com.adccadc.rust.block.Modblocks;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

public class HoneyMap {
    // 涂蜡方块集合
    public static final Set<Block> WAXED_BLOCKS = new HashSet<>();
    static {
        WAXED_BLOCKS.add(Modblocks.WAXED_IRON_BLOCK);
        WAXED_BLOCKS.add(Modblocks.WAXED_WEATHERED_IRON_BLOCK);
        WAXED_BLOCKS.add(Modblocks.WAXED_EXPOSED_IRON_BLOCK);
        WAXED_BLOCKS.add(Modblocks.WAXED_OXIDIZED_IRON_BLOCK);

        WAXED_BLOCKS.add(Modblocks.WAXED_IRON_BARS);
        WAXED_BLOCKS.add(Modblocks.WAXED_WEATHERED_IRON_BARS);
        WAXED_BLOCKS.add(Modblocks.WAXED_EXPOSED_IRON_BARS);
        WAXED_BLOCKS.add(Modblocks.WAXED_OXIDIZED_IRON_BARS);

        WAXED_BLOCKS.add(Modblocks.WAXED_IRON_TRAPDOOR);
        WAXED_BLOCKS.add(Modblocks.WAXED_WEATHERED_IRON_TRAPDOOR);
        WAXED_BLOCKS.add(Modblocks.WAXED_EXPOSED_IRON_TRAPDOOR);
        WAXED_BLOCKS.add(Modblocks.WAXED_OXIDIZED_IRON_TRAPDOOR);

        WAXED_BLOCKS.add(Modblocks.WAXED_IRON_CHAIN);
        WAXED_BLOCKS.add(Modblocks.WAXED_WEATHERED_IRON_CHAIN);
        WAXED_BLOCKS.add(Modblocks.WAXED_EXPOSED_IRON_CHAIN);
        WAXED_BLOCKS.add(Modblocks.WAXED_OXIDIZED_IRON_CHAIN);

        WAXED_BLOCKS.add(Modblocks.WAXED_IRON_DOOR);
        WAXED_BLOCKS.add(Modblocks.WAXED_WEATHERED_IRON_DOOR);
        WAXED_BLOCKS.add(Modblocks.WAXED_EXPOSED_IRON_DOOR);
        WAXED_BLOCKS.add(Modblocks.WAXED_OXIDIZED_IRON_DOOR);

        WAXED_BLOCKS.add(Modblocks.WAXED_HEAVY_WEIGHTED_PRESSURE_PLATE);
        WAXED_BLOCKS.add(Modblocks.WAXED_WEATHERED_HEAVY_WEIGHTED_PRESSURE_PLATE);
        WAXED_BLOCKS.add(Modblocks.WAXED_EXPOSED_HEAVY_WEIGHTED_PRESSURE_PLATE);
        WAXED_BLOCKS.add(Modblocks.WAXED_OXIDIZED_HEAVY_WEIGHTED_PRESSURE_PLATE);

        /*WAXED_BLOCKS.add(Modblocks.WAXED_CAULDRON);
        WAXED_BLOCKS.add(Modblocks.WAXED_WEATHERED_CAULDRON);
        WAXED_BLOCKS.add(Modblocks.WAXED_EXPOSED_CAULDRON);
        WAXED_BLOCKS.add(Modblocks.WAXED_OXIDIZED_CAULDRON);*/

        WAXED_BLOCKS.add(Modblocks.WAXED_LANTERN);
        WAXED_BLOCKS.add(Modblocks.WAXED_WEATHERED_LANTERN);
        WAXED_BLOCKS.add(Modblocks.WAXED_EXPOSED_LANTERN);
        WAXED_BLOCKS.add(Modblocks.WAXED_OXIDIZED_LANTERN);

        WAXED_BLOCKS.add(Modblocks.WAXED_SOUL_LANTERN);
        WAXED_BLOCKS.add(Modblocks.WAXED_WEATHERED_SOUL_LANTERN);
        WAXED_BLOCKS.add(Modblocks.WAXED_EXPOSED_SOUL_LANTERN);
        WAXED_BLOCKS.add(Modblocks.WAXED_OXIDIZED_SOUL_LANTERN);
    }
    // 涂蜡映射
    public static final Map<Block, Block> WAXABLE_BLOCKS = new HashMap<>();
    static {
        WAXABLE_BLOCKS.put(Blocks.IRON_BLOCK, Modblocks.WAXED_IRON_BLOCK);
        WAXABLE_BLOCKS.put(Modblocks.WEATHERED_IRON_BLOCK, Modblocks.WAXED_WEATHERED_IRON_BLOCK);
        WAXABLE_BLOCKS.put(Modblocks.EXPOSED_IRON_BLOCK, Modblocks.WAXED_EXPOSED_IRON_BLOCK);
        WAXABLE_BLOCKS.put(Modblocks.OXIDIZED_IRON_BLOCK, Modblocks.WAXED_OXIDIZED_IRON_BLOCK);

        WAXABLE_BLOCKS.put(Blocks.IRON_BARS, Modblocks.WAXED_IRON_BARS);
        WAXABLE_BLOCKS.put(Modblocks.WEATHERED_IRON_BARS, Modblocks.WAXED_WEATHERED_IRON_BARS);
        WAXABLE_BLOCKS.put(Modblocks.EXPOSED_IRON_BARS, Modblocks.WAXED_EXPOSED_IRON_BARS);
        WAXABLE_BLOCKS.put(Modblocks.OXIDIZED_IRON_BARS, Modblocks.WAXED_OXIDIZED_IRON_BARS);

        WAXABLE_BLOCKS.put(Blocks.IRON_TRAPDOOR, Modblocks.WAXED_IRON_TRAPDOOR);
        WAXABLE_BLOCKS.put(Modblocks.WEATHERED_IRON_TRAPDOOR, Modblocks.WAXED_WEATHERED_IRON_TRAPDOOR);
        WAXABLE_BLOCKS.put(Modblocks.EXPOSED_IRON_TRAPDOOR, Modblocks.WAXED_EXPOSED_IRON_TRAPDOOR);
        WAXABLE_BLOCKS.put(Modblocks.OXIDIZED_IRON_TRAPDOOR, Modblocks.WAXED_OXIDIZED_IRON_TRAPDOOR);

        WAXABLE_BLOCKS.put(Blocks.CHAIN, Modblocks.WAXED_IRON_CHAIN);
        WAXABLE_BLOCKS.put(Modblocks.WEATHERED_IRON_CHAIN, Modblocks.WAXED_WEATHERED_IRON_CHAIN);
        WAXABLE_BLOCKS.put(Modblocks.EXPOSED_IRON_CHAIN, Modblocks.WAXED_EXPOSED_IRON_CHAIN);
        WAXABLE_BLOCKS.put(Modblocks.OXIDIZED_IRON_CHAIN, Modblocks.WAXED_OXIDIZED_IRON_CHAIN);

        WAXABLE_BLOCKS.put(Blocks.IRON_DOOR, Modblocks.WAXED_IRON_DOOR);
        WAXABLE_BLOCKS.put(Modblocks.WEATHERED_IRON_DOOR, Modblocks.WAXED_WEATHERED_IRON_DOOR);
        WAXABLE_BLOCKS.put(Modblocks.EXPOSED_IRON_DOOR, Modblocks.WAXED_EXPOSED_IRON_DOOR);
        WAXABLE_BLOCKS.put(Modblocks.OXIDIZED_IRON_DOOR, Modblocks.WAXED_OXIDIZED_IRON_DOOR);

        WAXABLE_BLOCKS.put(Blocks.HEAVY_WEIGHTED_PRESSURE_PLATE, Modblocks.WAXED_HEAVY_WEIGHTED_PRESSURE_PLATE);
        WAXABLE_BLOCKS.put(Modblocks.WEATHERED_HEAVY_WEIGHTED_PRESSURE_PLATE, Modblocks.WAXED_WEATHERED_HEAVY_WEIGHTED_PRESSURE_PLATE);
        WAXABLE_BLOCKS.put(Modblocks.EXPOSED_HEAVY_WEIGHTED_PRESSURE_PLATE, Modblocks.WAXED_EXPOSED_HEAVY_WEIGHTED_PRESSURE_PLATE);
        WAXABLE_BLOCKS.put(Modblocks.OXIDIZED_HEAVY_WEIGHTED_PRESSURE_PLATE, Modblocks.WAXED_OXIDIZED_HEAVY_WEIGHTED_PRESSURE_PLATE);

        /*WAXABLE_BLOCKS.put(Blocks.CAULDRON, Modblocks.WAXED_CAULDRON);
        WAXABLE_BLOCKS.put(Modblocks.WEATHERED_CAULDRON, Modblocks.WAXED_WEATHERED_CAULDRON);
        WAXABLE_BLOCKS.put(Modblocks.EXPOSED_CAULDRON, Modblocks.WAXED_EXPOSED_CAULDRON);
        WAXABLE_BLOCKS.put(Modblocks.OXIDIZED_CAULDRON, Modblocks.WAXED_OXIDIZED_CAULDRON);*/

        WAXABLE_BLOCKS.put(Blocks.LANTERN, Modblocks.WAXED_LANTERN);
        WAXABLE_BLOCKS.put(Modblocks.WEATHERED_LANTERN, Modblocks.WAXED_WEATHERED_LANTERN);
        WAXABLE_BLOCKS.put(Modblocks.EXPOSED_LANTERN, Modblocks.WAXED_EXPOSED_LANTERN);
        WAXABLE_BLOCKS.put(Modblocks.OXIDIZED_LANTERN, Modblocks.WAXED_OXIDIZED_LANTERN);

        WAXABLE_BLOCKS.put(Blocks.SOUL_LANTERN, Modblocks.WAXED_SOUL_LANTERN);
        WAXABLE_BLOCKS.put(Modblocks.WEATHERED_SOUL_LANTERN, Modblocks.WAXED_WEATHERED_SOUL_LANTERN);
        WAXABLE_BLOCKS.put(Modblocks.EXPOSED_SOUL_LANTERN, Modblocks.WAXED_EXPOSED_SOUL_LANTERN);
        WAXABLE_BLOCKS.put(Modblocks.OXIDIZED_SOUL_LANTERN, Modblocks.WAXED_OXIDIZED_SOUL_LANTERN);
    }
    public static Map<Block, Block> getWaxableBlocks() {
        return WAXABLE_BLOCKS;
    }
    // 除蜡映射
    public static final Map<Block, Block> UNWAXABLE_BLOCKS = new HashMap<>();
    static {
        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_IRON_BLOCK, Blocks.IRON_BLOCK);
        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_WEATHERED_IRON_BLOCK, Modblocks.WEATHERED_IRON_BLOCK);
        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_EXPOSED_IRON_BLOCK, Modblocks.EXPOSED_IRON_BLOCK);
        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_OXIDIZED_IRON_BLOCK, Modblocks.OXIDIZED_IRON_BLOCK);

        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_IRON_BARS, Blocks.IRON_BARS);
        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_WEATHERED_IRON_BARS, Modblocks.WEATHERED_IRON_BARS);
        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_EXPOSED_IRON_BARS, Modblocks.EXPOSED_IRON_BARS);
        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_OXIDIZED_IRON_BARS, Modblocks.OXIDIZED_IRON_BARS);

        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_IRON_TRAPDOOR, Blocks.IRON_TRAPDOOR);
        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_WEATHERED_IRON_TRAPDOOR, Modblocks.WEATHERED_IRON_TRAPDOOR);
        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_EXPOSED_IRON_TRAPDOOR, Modblocks.EXPOSED_IRON_TRAPDOOR);
        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_OXIDIZED_IRON_TRAPDOOR, Modblocks.OXIDIZED_IRON_TRAPDOOR);

        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_IRON_CHAIN, Blocks.CHAIN);
        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_WEATHERED_IRON_CHAIN, Modblocks.WEATHERED_IRON_CHAIN);
        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_EXPOSED_IRON_CHAIN, Modblocks.EXPOSED_IRON_CHAIN);
        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_OXIDIZED_IRON_CHAIN, Modblocks.OXIDIZED_IRON_CHAIN);

        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_IRON_DOOR, Blocks.IRON_DOOR);
        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_WEATHERED_IRON_DOOR, Modblocks.WEATHERED_IRON_DOOR);
        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_EXPOSED_IRON_DOOR, Modblocks.EXPOSED_IRON_DOOR);
        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_OXIDIZED_IRON_DOOR, Modblocks.OXIDIZED_IRON_DOOR);

        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_HEAVY_WEIGHTED_PRESSURE_PLATE, Blocks.HEAVY_WEIGHTED_PRESSURE_PLATE);
        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_WEATHERED_HEAVY_WEIGHTED_PRESSURE_PLATE, Modblocks.WEATHERED_HEAVY_WEIGHTED_PRESSURE_PLATE);
        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_EXPOSED_HEAVY_WEIGHTED_PRESSURE_PLATE, Modblocks.EXPOSED_HEAVY_WEIGHTED_PRESSURE_PLATE);
        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_OXIDIZED_HEAVY_WEIGHTED_PRESSURE_PLATE, Modblocks.OXIDIZED_HEAVY_WEIGHTED_PRESSURE_PLATE);

        /*UNWAXABLE_BLOCKS.put(Modblocks.WAXED_CAULDRON, Blocks.CAULDRON);
        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_WEATHERED_CAULDRON, Modblocks.WEATHERED_CAULDRON);
        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_EXPOSED_CAULDRON, Modblocks.EXPOSED_CAULDRON);
        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_OXIDIZED_CAULDRON, Modblocks.OXIDIZED_CAULDRON);*/

        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_LANTERN, Blocks.LANTERN);
        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_WEATHERED_LANTERN, Modblocks.WEATHERED_LANTERN);
        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_EXPOSED_LANTERN, Modblocks.EXPOSED_LANTERN);
        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_OXIDIZED_LANTERN, Modblocks.OXIDIZED_LANTERN);

        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_SOUL_LANTERN, Blocks.SOUL_LANTERN);
        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_WEATHERED_SOUL_LANTERN, Modblocks.WEATHERED_SOUL_LANTERN);
        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_EXPOSED_SOUL_LANTERN, Modblocks.EXPOSED_SOUL_LANTERN);
        UNWAXABLE_BLOCKS.put(Modblocks.WAXED_OXIDIZED_SOUL_LANTERN, Modblocks.OXIDIZED_SOUL_LANTERN);
    }
}
