package com.adccadc.rust;

import com.adccadc.rust.block.Modblocks;
import com.google.common.base.Suppliers;
import com.google.common.collect.BiMap;
import com.google.common.collect.ImmutableBiMap;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;

import java.util.HashMap;
import java.util.Map;
import java.util.function.Supplier;

public class OxidizeMap {

    public static Supplier<BiMap<Block, Block>> MOD_OXIDATION_LEVEL_INCREASES = Suppliers.memoize(() -> ImmutableBiMap.<Block, Block>builder()
            .put(Blocks.COPPER_BLOCK, Blocks.EXPOSED_COPPER).put(Blocks.EXPOSED_COPPER, Blocks.WEATHERED_COPPER).put(Blocks.WEATHERED_COPPER, Blocks.OXIDIZED_COPPER)
            .put(Blocks.CUT_COPPER, Blocks.EXPOSED_CUT_COPPER).put(Blocks.EXPOSED_CUT_COPPER, Blocks.WEATHERED_CUT_COPPER).put(Blocks.WEATHERED_CUT_COPPER, Blocks.OXIDIZED_CUT_COPPER)
            .put(Blocks.CHISELED_COPPER, Blocks.EXPOSED_CHISELED_COPPER).put(Blocks.EXPOSED_CHISELED_COPPER, Blocks.WEATHERED_CHISELED_COPPER).put(Blocks.WEATHERED_CHISELED_COPPER, Blocks.OXIDIZED_CHISELED_COPPER)
            .put(Blocks.CUT_COPPER_SLAB, Blocks.EXPOSED_CUT_COPPER_SLAB).put(Blocks.EXPOSED_CUT_COPPER_SLAB, Blocks.WEATHERED_CUT_COPPER_SLAB).put(Blocks.WEATHERED_CUT_COPPER_SLAB, Blocks.OXIDIZED_CUT_COPPER_SLAB)
            .put(Blocks.CUT_COPPER_STAIRS, Blocks.EXPOSED_CUT_COPPER_STAIRS).put(Blocks.EXPOSED_CUT_COPPER_STAIRS, Blocks.WEATHERED_CUT_COPPER_STAIRS).put(Blocks.WEATHERED_CUT_COPPER_STAIRS, Blocks.OXIDIZED_CUT_COPPER_STAIRS)
            .put(Blocks.COPPER_DOOR, Blocks.EXPOSED_COPPER_DOOR).put(Blocks.EXPOSED_COPPER_DOOR, Blocks.WEATHERED_COPPER_DOOR).put(Blocks.WEATHERED_COPPER_DOOR, Blocks.OXIDIZED_COPPER_DOOR)
            .put(Blocks.COPPER_TRAPDOOR, Blocks.EXPOSED_COPPER_TRAPDOOR).put(Blocks.EXPOSED_COPPER_TRAPDOOR, Blocks.WEATHERED_COPPER_TRAPDOOR).put(Blocks.WEATHERED_COPPER_TRAPDOOR, Blocks.OXIDIZED_COPPER_TRAPDOOR)
            .put(Blocks.COPPER_GRATE, Blocks.EXPOSED_COPPER_GRATE).put(Blocks.EXPOSED_COPPER_GRATE, Blocks.WEATHERED_COPPER_GRATE).put(Blocks.WEATHERED_COPPER_GRATE, Blocks.OXIDIZED_COPPER_GRATE)
            .put(Blocks.COPPER_BULB, Blocks.EXPOSED_COPPER_BULB).put(Blocks.EXPOSED_COPPER_BULB, Blocks.WEATHERED_COPPER_BULB).put(Blocks.WEATHERED_COPPER_BULB, Blocks.OXIDIZED_COPPER_BULB)
            .put(Blocks.IRON_BLOCK, Modblocks.EXPOSED_IRON_BLOCK).put(Modblocks.EXPOSED_IRON_BLOCK, Modblocks.WEATHERED_IRON_BLOCK).put(Modblocks.WEATHERED_IRON_BLOCK, Modblocks.OXIDIZED_IRON_BLOCK)
            .put(Blocks.IRON_BARS, Modblocks.EXPOSED_IRON_BARS).put(Modblocks.EXPOSED_IRON_BARS, Modblocks.WEATHERED_IRON_BARS).put(Modblocks.WEATHERED_IRON_BARS, Modblocks.OXIDIZED_IRON_BARS)
            .put(Blocks.IRON_TRAPDOOR, Modblocks.EXPOSED_IRON_TRAPDOOR).put(Modblocks.EXPOSED_IRON_TRAPDOOR, Modblocks.WEATHERED_IRON_TRAPDOOR).put(Modblocks.WEATHERED_IRON_TRAPDOOR, Modblocks.OXIDIZED_IRON_TRAPDOOR)
            .put(Blocks.IRON_DOOR, Modblocks.EXPOSED_IRON_DOOR).put(Modblocks.EXPOSED_IRON_DOOR, Modblocks.WEATHERED_IRON_DOOR).put(Modblocks.WEATHERED_IRON_DOOR, Modblocks.OXIDIZED_IRON_DOOR)
            .put(Blocks.CHAIN, Modblocks.EXPOSED_IRON_CHAIN).put(Modblocks.EXPOSED_IRON_CHAIN, Modblocks.WEATHERED_IRON_CHAIN).put(Modblocks.WEATHERED_IRON_CHAIN, Modblocks.OXIDIZED_IRON_CHAIN)
            .put(Blocks.HEAVY_WEIGHTED_PRESSURE_PLATE, Modblocks.EXPOSED_HEAVY_WEIGHTED_PRESSURE_PLATE).put(Modblocks.EXPOSED_HEAVY_WEIGHTED_PRESSURE_PLATE, Modblocks.WEATHERED_HEAVY_WEIGHTED_PRESSURE_PLATE).put(Modblocks.WEATHERED_HEAVY_WEIGHTED_PRESSURE_PLATE, Modblocks.OXIDIZED_HEAVY_WEIGHTED_PRESSURE_PLATE)
            .put(Blocks.LANTERN, Modblocks.EXPOSED_LANTERN).put(Modblocks.EXPOSED_LANTERN, Modblocks.WEATHERED_LANTERN).put(Modblocks.WEATHERED_LANTERN, Modblocks.OXIDIZED_LANTERN)
            .put(Blocks.SOUL_LANTERN, Modblocks.EXPOSED_SOUL_LANTERN).put(Modblocks.EXPOSED_SOUL_LANTERN, Modblocks.WEATHERED_SOUL_LANTERN).put(Modblocks.WEATHERED_SOUL_LANTERN, Modblocks.OXIDIZED_SOUL_LANTERN)
            .build());

    public static Supplier<BiMap<Block, Block>> MOD_OXIDATION_LEVEL_DECREASES = Suppliers.memoize(() -> ((BiMap)MOD_OXIDATION_LEVEL_INCREASES.get()).inverse());

    // 铁质方块氧化映射
    @Deprecated
    public static final Map<Block, Block> IRONBLOCK_OXIDATION_MAP = new HashMap<>();
    static {
        IRONBLOCK_OXIDATION_MAP.put(Blocks.IRON_BLOCK, Modblocks.EXPOSED_IRON_BLOCK);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.EXPOSED_IRON_BLOCK, Modblocks.WEATHERED_IRON_BLOCK);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.WEATHERED_IRON_BLOCK, Modblocks.OXIDIZED_IRON_BLOCK);

        IRONBLOCK_OXIDATION_MAP.put(Blocks.IRON_BARS, Modblocks.EXPOSED_IRON_BARS);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.EXPOSED_IRON_BARS, Modblocks.WEATHERED_IRON_BARS);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.WEATHERED_IRON_BARS, Modblocks.OXIDIZED_IRON_BARS);

        IRONBLOCK_OXIDATION_MAP.put(Blocks.IRON_TRAPDOOR, Modblocks.EXPOSED_IRON_TRAPDOOR);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.EXPOSED_IRON_TRAPDOOR, Modblocks.WEATHERED_IRON_TRAPDOOR);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.WEATHERED_IRON_TRAPDOOR, Modblocks.OXIDIZED_IRON_TRAPDOOR);

        IRONBLOCK_OXIDATION_MAP.put(Blocks.CHAIN, Modblocks.EXPOSED_IRON_CHAIN);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.EXPOSED_IRON_CHAIN, Modblocks.WEATHERED_IRON_CHAIN);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.WEATHERED_IRON_CHAIN, Modblocks.OXIDIZED_IRON_CHAIN);

        IRONBLOCK_OXIDATION_MAP.put(Blocks.IRON_DOOR, Modblocks.EXPOSED_IRON_DOOR);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.EXPOSED_IRON_DOOR, Modblocks.WEATHERED_IRON_DOOR);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.WEATHERED_IRON_DOOR, Modblocks.OXIDIZED_IRON_DOOR);

        IRONBLOCK_OXIDATION_MAP.put(Blocks.HEAVY_WEIGHTED_PRESSURE_PLATE, Modblocks.EXPOSED_HEAVY_WEIGHTED_PRESSURE_PLATE);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.EXPOSED_HEAVY_WEIGHTED_PRESSURE_PLATE, Modblocks.WEATHERED_HEAVY_WEIGHTED_PRESSURE_PLATE);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.WEATHERED_HEAVY_WEIGHTED_PRESSURE_PLATE, Modblocks.OXIDIZED_HEAVY_WEIGHTED_PRESSURE_PLATE);

        /*IRONBLOCK_OXIDATION_MAP.put(Blocks.CAULDRON, Modblocks.EXPOSED_CAULDRON);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.EXPOSED_CAULDRON, Modblocks.WEATHERED_CAULDRON);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.WEATHERED_CAULDRON, Modblocks.OXIDIZED_CAULDRON);*/

        IRONBLOCK_OXIDATION_MAP.put(Blocks.LANTERN, Modblocks.EXPOSED_LANTERN);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.EXPOSED_LANTERN, Modblocks.WEATHERED_LANTERN);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.WEATHERED_LANTERN, Modblocks.OXIDIZED_LANTERN);

        IRONBLOCK_OXIDATION_MAP.put(Blocks.SOUL_LANTERN, Modblocks.EXPOSED_SOUL_LANTERN);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.EXPOSED_SOUL_LANTERN, Modblocks.WEATHERED_SOUL_LANTERN);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.WEATHERED_SOUL_LANTERN, Modblocks.OXIDIZED_SOUL_LANTERN);
    }
    // 铁质方块除锈映射
    public static final Map<Block, Block> IRONBLOCK_DEOXIDATION_MAP = new HashMap<>();
    static {
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.OXIDIZED_IRON_BLOCK, Modblocks.WEATHERED_IRON_BLOCK);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.WEATHERED_IRON_BLOCK, Modblocks.EXPOSED_IRON_BLOCK);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.EXPOSED_IRON_BLOCK, Blocks.IRON_BLOCK);

        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.OXIDIZED_IRON_BARS, Modblocks.WEATHERED_IRON_BARS);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.WEATHERED_IRON_BARS, Modblocks.EXPOSED_IRON_BARS);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.EXPOSED_IRON_BARS, Blocks.IRON_BARS);

        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.OXIDIZED_IRON_TRAPDOOR, Modblocks.WEATHERED_IRON_TRAPDOOR);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.WEATHERED_IRON_TRAPDOOR, Modblocks.EXPOSED_IRON_TRAPDOOR);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.EXPOSED_IRON_TRAPDOOR, Blocks.IRON_TRAPDOOR);

        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.OXIDIZED_IRON_CHAIN, Modblocks.WEATHERED_IRON_CHAIN);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.WEATHERED_IRON_CHAIN, Modblocks.EXPOSED_IRON_CHAIN);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.EXPOSED_IRON_CHAIN, Blocks.CHAIN);

        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.OXIDIZED_IRON_DOOR, Modblocks.WEATHERED_IRON_DOOR);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.WEATHERED_IRON_DOOR, Modblocks.EXPOSED_IRON_DOOR);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.EXPOSED_IRON_DOOR, Blocks.IRON_DOOR);

        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.OXIDIZED_HEAVY_WEIGHTED_PRESSURE_PLATE, Modblocks.WEATHERED_HEAVY_WEIGHTED_PRESSURE_PLATE);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.WEATHERED_HEAVY_WEIGHTED_PRESSURE_PLATE, Modblocks.EXPOSED_HEAVY_WEIGHTED_PRESSURE_PLATE);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.EXPOSED_HEAVY_WEIGHTED_PRESSURE_PLATE, Blocks.HEAVY_WEIGHTED_PRESSURE_PLATE);

        /*IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.OXIDIZED_CAULDRON, Modblocks.WEATHERED_CAULDRON);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.WEATHERED_CAULDRON, Modblocks.EXPOSED_CAULDRON);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.EXPOSED_CAULDRON, Blocks.CAULDRON);*/

        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.OXIDIZED_LANTERN, Modblocks.WEATHERED_LANTERN);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.WEATHERED_LANTERN, Modblocks.EXPOSED_LANTERN);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.EXPOSED_LANTERN, Blocks.LANTERN);

        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.OXIDIZED_SOUL_LANTERN, Modblocks.WEATHERED_SOUL_LANTERN);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.WEATHERED_SOUL_LANTERN, Modblocks.EXPOSED_SOUL_LANTERN);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.EXPOSED_SOUL_LANTERN, Blocks.SOUL_LANTERN);
    }
}
