package com.adccadc.rust;

import com.adccadc.rust.block.Modblocks;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;

import java.util.HashMap;
import java.util.Map;

public class OxidizeMap {
    // 铁质方块氧化映射
    public static final Map<Block, Block> IRONBLOCK_OXIDATION_MAP = new HashMap<>();
    static {
        IRONBLOCK_OXIDATION_MAP.put(Blocks.IRON_BLOCK, Modblocks.EXPOSED_IRON_BLOCK);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.EXPOSED_IRON_BLOCK, Modblocks.WEATHERED_IRON_BLOCK);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.WEATHERED_IRON_BLOCK, Modblocks.OXIDIZED_IRON_BLOCK);

        IRONBLOCK_OXIDATION_MAP.put(Blocks.IRON_BARS, Modblocks.EXPOSED_IRON_BARS);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.EXPOSED_IRON_BARS, Modblocks.WEATHERED_IRON_BARS);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.WEATHERED_IRON_BARS, Modblocks.OXIDIZED_IRON_BARS);

        IRONBLOCK_OXIDATION_MAP.put(Blocks.IRON_TRAPDOOR, Modblocks.EXPOSED_IRON_TRAPDOOR);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.EXPOSED_IRON_TRAPDOOR, Modblocks.WEATHERED_IRON_TRAPDOOR);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.WEATHERED_IRON_TRAPDOOR, Modblocks.OXIDIZED_IRON_TRAPDOOR);

        IRONBLOCK_OXIDATION_MAP.put(Blocks.CHAIN, Modblocks.EXPOSED_IRON_CHAIN);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.EXPOSED_IRON_CHAIN, Modblocks.WEATHERED_IRON_CHAIN);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.WEATHERED_IRON_CHAIN, Modblocks.OXIDIZED_IRON_CHAIN);

        IRONBLOCK_OXIDATION_MAP.put(Blocks.IRON_DOOR, Modblocks.EXPOSED_IRON_DOOR);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.EXPOSED_IRON_DOOR, Modblocks.WEATHERED_IRON_DOOR);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.WEATHERED_IRON_DOOR, Modblocks.OXIDIZED_IRON_DOOR);

        IRONBLOCK_OXIDATION_MAP.put(Blocks.HEAVY_WEIGHTED_PRESSURE_PLATE, Modblocks.EXPOSED_HEAVY_WEIGHTED_PRESSURE_PLATE);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.EXPOSED_HEAVY_WEIGHTED_PRESSURE_PLATE, Modblocks.WEATHERED_HEAVY_WEIGHTED_PRESSURE_PLATE);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.WEATHERED_HEAVY_WEIGHTED_PRESSURE_PLATE, Modblocks.OXIDIZED_HEAVY_WEIGHTED_PRESSURE_PLATE);

        /*IRONBLOCK_OXIDATION_MAP.put(Blocks.CAULDRON, Modblocks.EXPOSED_CAULDRON);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.EXPOSED_CAULDRON, Modblocks.WEATHERED_CAULDRON);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.WEATHERED_CAULDRON, Modblocks.OXIDIZED_CAULDRON);*/

        IRONBLOCK_OXIDATION_MAP.put(Blocks.LANTERN, Modblocks.EXPOSED_LANTERN);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.EXPOSED_LANTERN, Modblocks.WEATHERED_LANTERN);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.WEATHERED_LANTERN, Modblocks.OXIDIZED_LANTERN);

        IRONBLOCK_OXIDATION_MAP.put(Blocks.SOUL_LANTERN, Modblocks.EXPOSED_SOUL_LANTERN);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.EXPOSED_SOUL_LANTERN, Modblocks.WEATHERED_SOUL_LANTERN);
        IRONBLOCK_OXIDATION_MAP.put(Modblocks.WEATHERED_SOUL_LANTERN, Modblocks.OXIDIZED_SOUL_LANTERN);
    }
    // 铁质方块除锈映射
    public static final Map<Block, Block> IRONBLOCK_DEOXIDATION_MAP = new HashMap<>();
    static {
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.OXIDIZED_IRON_BLOCK, Modblocks.WEATHERED_IRON_BLOCK);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.WEATHERED_IRON_BLOCK, Modblocks.EXPOSED_IRON_BLOCK);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.EXPOSED_IRON_BLOCK, Blocks.IRON_BLOCK);

        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.OXIDIZED_IRON_BARS, Modblocks.WEATHERED_IRON_BARS);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.WEATHERED_IRON_BARS, Modblocks.EXPOSED_IRON_BARS);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.EXPOSED_IRON_BARS, Blocks.IRON_BARS);

        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.OXIDIZED_IRON_TRAPDOOR, Modblocks.WEATHERED_IRON_TRAPDOOR);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.WEATHERED_IRON_TRAPDOOR, Modblocks.EXPOSED_IRON_TRAPDOOR);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.EXPOSED_IRON_TRAPDOOR, Blocks.IRON_TRAPDOOR);

        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.OXIDIZED_IRON_CHAIN, Modblocks.WEATHERED_IRON_CHAIN);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.WEATHERED_IRON_CHAIN, Modblocks.EXPOSED_IRON_CHAIN);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.EXPOSED_IRON_CHAIN, Blocks.CHAIN);

        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.OXIDIZED_IRON_DOOR, Modblocks.WEATHERED_IRON_DOOR);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.WEATHERED_IRON_DOOR, Modblocks.EXPOSED_IRON_DOOR);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.EXPOSED_IRON_DOOR, Blocks.IRON_DOOR);

        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.OXIDIZED_HEAVY_WEIGHTED_PRESSURE_PLATE, Modblocks.WEATHERED_HEAVY_WEIGHTED_PRESSURE_PLATE);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.WEATHERED_HEAVY_WEIGHTED_PRESSURE_PLATE, Modblocks.EXPOSED_HEAVY_WEIGHTED_PRESSURE_PLATE);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.EXPOSED_HEAVY_WEIGHTED_PRESSURE_PLATE, Blocks.HEAVY_WEIGHTED_PRESSURE_PLATE);

        /*IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.OXIDIZED_CAULDRON, Modblocks.WEATHERED_CAULDRON);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.WEATHERED_CAULDRON, Modblocks.EXPOSED_CAULDRON);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.EXPOSED_CAULDRON, Blocks.CAULDRON);*/

        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.OXIDIZED_LANTERN, Modblocks.WEATHERED_LANTERN);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.WEATHERED_LANTERN, Modblocks.EXPOSED_LANTERN);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.EXPOSED_LANTERN, Blocks.LANTERN);

        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.OXIDIZED_SOUL_LANTERN, Modblocks.WEATHERED_SOUL_LANTERN);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.WEATHERED_SOUL_LANTERN, Modblocks.EXPOSED_SOUL_LANTERN);
        IRONBLOCK_DEOXIDATION_MAP.put(Modblocks.EXPOSED_SOUL_LANTERN, Blocks.SOUL_LANTERN);
    }
}
